name: 'Docker Hub'
description: 'Checkout, build Docker image, push to docker.io repository of same name with current tag and latest. You can use $TOKEN in your Dockerfile, and it will be replaced with your GITHUB_TOKEN secret.'

inputs:
  docker-hub-password:
    description: 'Password for the Docker Hub account with the same username as the owner of the repo you are pushing.'
    required: true

  npm-install-pat:
    description: 'PAT for any npm registry you might need to authenticate with, if you are installing private packages. Will replace $TOKEN in your Dockerfile.'
    required: false

runs:
  using: "composite"
  steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Add GitHub build token to Dockerfile
        shell: bash
        run: sed -i 's/\$TOKEN/${{ inputs.npm-install-pat }}/g' Dockerfile

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ github.repository }}
          tags: latest, ${{ github.ref_name }}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ github.repository_owner }}
          password: ${{ inputs.docker-hub-password }}
